AWSTemplateFormatVersion: "2010-09-09"
Description: Create a security group allowing inbound traffic on port 80

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0   # Allows access from any IP address. Adjust as needed.
      # VpcId: vpc-05539536d2e9a1e19
    DeletionPolicy: Retain

Outputs:
  SecurityGroupId:
    Description: The ID of the created security group
    Value: !Ref MySecurityGroup
